name: tileserver
services:
  app: 
    image: maptiler/tileserver-gl
    container_name: tileserver
    ports:
      - "8080:8080"
    volumes:
      - type: bind
        source: ./src
        target: /data